### PR TITLE
Added Video links

### PR DESCRIPTION
**Pull request by SunveerSingh**
Video links for Workshop 4. If any changes are needed, please let me know.

### CODE REVIEW

**Comment by cvvergara** [comment]
@SunveerSingh 
I don't know ...

Can you make another PR but with video links at the end of the section that is being taped instead of the beginning.
Maybe another one where the links are in a separate section at the end of the file

Then we can decide which one is best.

I also do that kinda thing, I have 3 PR right now in pgRouting, waiting for a decision

**Comment by SunveerSingh** [comment]
@cvvergara Please see #42 #43

**Comment by dkastl** [comment]
I would prefer to not have a sentence with link attached to every section. It's a bit hard to maintain. What about having a page with a list of all available video links?

Also I would not like to have my students watch videos during the workshop ;-)

**Comment by cvvergara** [comment]
@SunveerSingh 
make another PR, that is an individual page chapter for the all videos

**Comment by cvvergara** [comment]
Close in favor of #44

**Pull request closed without merging**
