### PR TITLE
Proposal organization

### PR DESCRIPTION
**Pull request by cvvergara**
This is Vicky's proposal
https://github.com/cvvergara/workshop/tree/proposal-organization/docs

This is the tree structure under `docs` directory
```
├── advanced
├── appendix
├── basic
│   └── images
│       ├── chapter4
│       ├── chapter5
│       ├── chapter6
│       ├── chapter7
│       └── chapter8
├── examples
│   └── images
│       └── hanosiav
├── general-intro
│   └── images
│       ├── chapter1
│       ├── chapter2
│       └── chapter3
├── images
├── interactions
│   ├── chap_QGIS
│   ├── chapter9
│   └── code
├── scripts
│   ├── chapter_4
│   ├── chapter_5
│   ├── chapter_6
│   ├── chapter_7
│   ├── chapter_8
│   ├── configuration
│   └── un_sdg
├── source
│   └── _themes
├── _static
│   └── images
├── _templates
├── _themes
└── un_sdg
    └── images
```

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
links will change eventually to something like:
from this:
https://workshop.pgrouting.org/dev/en/chapters/chapter-5.html
to this
https://workshop.pgrouting.org/dev/en/basic/chapter-5.html

**Comment by dkastl** [comment]
Is there a way to make the URL segment different from the folder or file name?

For example the following would be good URLs:
```
en/intro/01.html
en/intro/02.html
...
en/basic/01.html
en/basic/02.html
en/basic/03.html
```
... or even with understandable names rather than numbers.

**Comment by omshinde** [comment]
Hi @cvvergara
Here's my proposal: #166 

@cvvergara - I have kept the structure as suggested by you for uniformity except my following additions:

- Putting `un_sdg` in a directory named `case-studies`. The idea is that if someone is only interested in following the case-studies then all of the case studies can be compiled together. The case studies to be implemented in future also goes in this directory.
- I think `general-intro` should be named as `getting-started` as `general-intro` tempts me to skip that part.

I agree with rest of the structure. Thanks!

**Comment by omshinde** [comment]
> Is there a way to make the URL segment different from the folder or file name?
> 
> For example the following would be good URLs:
> 
> ```
> en/intro/01.html
> en/intro/02.html
> ...
> en/basic/01.html
> en/basic/02.html
> en/basic/03.html
> ```
> 
> ... or even with understandable names rather than numbers.

@dkastl I think this is great idea. But for `basic` and `general-intro` exercises keeping understandable names might lead to confusion. For instance, if I see `Chapter5.html` as `pgroutingAlgorithm.html`, I feel like going to Chapter 5 directly skipping Chapter 1, 2, 3, 4 which might lead to issues later as the setup is not complete. (maybe this is my oversight :-) ) Thanks!

**Pull request closed without merging**
